/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 panther.gltf 
Author: Neut2000 (https://sketchfab.com/Neut2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fortnite-daredevil-version-1-9219d4d9131241fbb7d6fe3f0dc6c937
Title: Fortnite Daredevil Version 1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/panther.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Model001_Material001} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Model001_Material002} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Model001_Material003} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Model001_Material004} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Model001_Material005} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Model001_Material006} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Model001_Material007} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Model001_Material008} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Model001_Material009} />
      </group>
    </group>
  )
}

useGLTF.preload('/panther.gltf')
